### ISSUE TITLE
#1 Despliegue: Ejecutable - Pruebas - calidad

### ISSUE THREAD

**Issue by moi0006** [moi0006/GESPRO_PracticaGestionCodigo#1]
Crear el ejecutable con el ANT.

**Comment by moi0006** [comment]
Ya se puede utilizar el ant correctamente. Yo lo he probado en varias ocasiones en lugares diferentes y me ha funcionado. Si tienes cualquier problema me dices.

 - Sincronízate con el repositorio.

 - Ejecuta los siguientes comandos. (Te recomiendo que uses el clean para eliminar todas las carpetas que genera el ANT)

`ant clean`

`ant [runnable]`

En la carpeta runnable ejecuta el siguiente comando:

`java -jar SistInfGenWeb.jar [nivel]`

**Comment by fma0043** [comment]
La tarea javadoc tiene errores Añadir una taraea de test JUnit/DBUnit para probar La Fachada de acceso a datos. Incorporar la cobertura de pruebas (SonarCube o Eclemma)

**Comment by fma0043** [comment]
changed title to Despliegue: Ejecutable - Pruebas - calidad

**Comment by moi0006** [comment]
CIerto, parece que los errores provienen por la codificación! Voy a ponerla correctamente en UTF8

**Comment by fma0043** [comment]
Perfecto, después de cambiar la codificación ya está bien

**Comment by fma0043** [comment]
He actualizado las dependencias de la documentación

**Comment by moi0006** [comment]
Perfecto! Buen trabajo!
