### ISSUE TITLE
#3 Actualizada la url del calendario GCalendar.

### ISSUE THREAD

**Issue by moi0006** [moi0006/GESPRO_PracticaGestionCodigo#3]
Actualizada la url del calendario GCalendar.
Refactorizar en el futuro para incluirla como propiedad

**Comment by moi0006** [comment]
@fma0043 ¡Ponte a ello!

**Comment by fma0043** [comment]
Ya está terminado

**Comment by moi0006** [comment]
¡Perfecto!
