### ISSUE TITLE
#4 Distribuir las propiedades

### ISSUE THREAD

**Issue by fma0043** [moi0006/GESPRO_PracticaGestionCodigo#4]
Distribuir las propiedades cuando se genera runnable para no depender
del fuente.

**Comment by moi0006** [comment]
¡A ello!

**Comment by fma0043** [comment]
Creo que te has dejado el Generator.java revisalo!! @moi0006

**Comment by moi0006** [comment]
Cierto! gracias. Me pongo a ello!

**Comment by fma0043** [comment]
Así mejor, perfecto!
